// <auto-generated />
using System;
using Car_Rent_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Rent_System.Migrations
{
    [DbContext(typeof(CynexBlazerContext))]
    [Migration("20250722005108_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Rent_System.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BookingID");

                    b.HasIndex("CarID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Car_Rent_System.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarID"));

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<double?>("Mileage")
                        .HasColumnType("float");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CarID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            CarModel = "2024",
                            CarName = "BMW M5 Competition",
                            CarType = "Luxury Sedan",
                            DailyRate = 299.00m,
                            DateAdded = new DateTime(2025, 7, 22, 9, 51, 7, 677, DateTimeKind.Local).AddTicks(6298),
                            Description = "Experience ultimate luxury and performance with the BMW M5 Competition.",
                            FuelType = "Petrol",
                            ImageUrl = "~/images/BMW.jpg",
                            IsAvailable = true,
                            Mileage = 12.5,
                            SeatingCapacity = 5,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarID = 2,
                            CarModel = "2024",
                            CarName = "Mercedes-AMG G63",
                            CarType = "Luxury SUV",
                            DailyRate = 399.00m,
                            DateAdded = new DateTime(2025, 7, 22, 9, 51, 7, 677, DateTimeKind.Local).AddTicks(6460),
                            Description = "Conquer any terrain with the iconic Mercedes-AMG G63 SUV.",
                            FuelType = "Petrol",
                            ImageUrl = "~/images/Mercedes.jpg",
                            IsAvailable = true,
                            Mileage = 10.199999999999999,
                            SeatingCapacity = 7,
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarID = 3,
                            CarModel = "2024",
                            CarName = "Lamborghini Huracán",
                            CarType = "Supercar",
                            DailyRate = 899.00m,
                            DateAdded = new DateTime(2025, 7, 22, 9, 51, 7, 677, DateTimeKind.Local).AddTicks(6465),
                            Description = "Feel the thrill of Italian engineering with the Lamborghini Huracán.",
                            FuelType = "Petrol",
                            ImageUrl = "~/images/Lambogini.jpg",
                            IsAvailable = true,
                            Mileage = 8.5,
                            SeatingCapacity = 2,
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("Car_Rent_System.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            DateJoined = new DateTime(2025, 7, 22, 9, 51, 7, 676, DateTimeKind.Local).AddTicks(6841),
                            Email = "admin@cynexblazer.com",
                            FullName = "CYNEX BLAZER Administrator",
                            IsActive = true,
                            Password = "admin123",
                            PhoneNumber = "+1234567890",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Car_Rent_System.Models.Booking", b =>
                {
                    b.HasOne("Car_Rent_System.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car_Rent_System.Models.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Car_Rent_System.Models.Car", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Car_Rent_System.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
